development:
  adapter: postgresql
  encoding: unicode
  database: foodomatic_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: foodomatic_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: foodomatic
  pool: 5
  username:
  password:
  timeout: 5000
