recipe = Recipe.create(title: 'Mustard Seed Ramen', image_url: 'http://i.imgur.com/Su2lQ3B.jpg')
recipe.Product.create(name: "mustard seeds", amount_type: unit, price: "1.50", min_amount: 1)
recipe.Product.create(name: "vegetable broth", amount_type: unit, price: "2.50", min_amount: 1)
recipe.Product.create(name: "noodles", amount_type: unit, price: "2.00", min_amount: 1)
recipe.Product.create(name: "green onions", amount_type: unit, price: "1.00", min_amount: 1)

recipe = Recipe.create(title: 'Vegatarian Meatballs', image_url: 'http://blog.hostthetoast.com/wp-content/uploads/2013/09/8-30-13-070.jpg')
recipe.Product.create(name: "chickpea flour", amount_type: unit, price: "1.50", min_amount: 1)
recipe.Product.create(name: "toasted walnuts", amount_type: unit, price: "2.50", min_amount: 1)
recipe.Product.create(name: "olive oil", amount_type: unit, price: "2.00", min_amount: 1)
recipe.Product.create(name: "garlic", amount_type: unit, price: "1.00", min_amount: 1)

recipe = Recipe.create(title: 'Smore Hot Chocolate for You', image_url: 'http://31.media.tumblr.com/27fc9328b1b7d915ffdc30d67f789420/tumblr_mezlo6kYnZ1rslfxoo1_500.jpg')
recipe.Product.create(name: "mini marshmallows", amount_type: unit, price: "1.50", min_amount: 1)
recipe.Product.create(name: "hot cocoa mix", amount_type: unit, price: "2.50", min_amount: 1)
recipe.Product.create(name: "chocolate syrup", amount_type: unit, price: "2.00", min_amount: 1)


recipe = Recipe.create(title: 'Unagi Rolls', image_url: 'http://farm3.staticflickr.com/2849/9729531511_cd23815119_b.jpg')
recipe.Product.create(name: "rice", amount_type: unit, price: "1.50", min_amount: 1)
recipe.Product.create(name: "nori", amount_type: unit, price: "3.50", min_amount: 1)
recipe.Product.create(name: "avocado", amount_type: unit, price: "7.00", min_amount: 1)
recipe.Product.create(name: "freshwater eel", amount_type: unit, price: "10.00", min_amount: 1)


recipe = Recipe.create(title: 'Chili Kale Burger', image_url: 'http://i.imgur.com/DZuH6FH.jpg')
recipe.Product.create(name: "brioche buns", amount_type: unit, price: "1.50", min_amount: 1)
recipe.Product.create(name: "ground chuck", amount_type: unit, price: "3.50", min_amount: 1)
recipe.Product.create(name: "beef chili", amount_type: unit, price: "7.00", min_amount: 1)
recipe.Product.create(name: "Russian red kale", amount_type: unit, price: "10.00", min_amount: 1)

recipe = Recipe.create(title: 'Weird Mystery Stew', image_url: 'http://farm6.staticflickr.com/5496/9730454498_8fba7dbb2f_h.jpg')
recipe.Product.create(name: "blood sausage", amount_type: unit, price: "4.50", min_amount: 1)
recipe.Product.create(name: "green onions", amount_type: unit, price: "1.50", min_amount: 1)
recipe.Product.create(name: "sesame seeds", amount_type: unit, price: "2.00", min_amount: 1)
recipe.Product.create(name: "chicken broth", amount_type: unit, price: "3.00", min_amount: 1)

recipe = Recipe.create(title: 'Pork Belly Tacos', image_url: 'http://i.imgur.com/IWUnZR6.jpg')
recipe.Product.create(name: "pork belly", amount_type: unit, price: "4.50", min_amount: 1)
recipe.Product.create(name: "cilantro", amount_type: unit, price: "1.50", min_amount: 1)
recipe.Product.create(name: "limes", amount_type: unit, price: "1.00", min_amount: 1)
recipe.Product.create(name: "tortillas", amount_type: unit, price: "2.00", min_amount: 1)

recipe = Recipe.create(title: 'Fried Cheese Raviolis', image_url: 'http://i.imgur.com/8nuolGP.jpg#.UVIfdXvd27k.reddit')
recipe.Product.create(name: "frozen cheese raviolis", amount_type: unit, price: "4.50", min_amount: 1)
recipe.Product.create(name: "parmesan cheese", amount_type: unit, price: "4.50", min_amount: 1)
recipe.Product.create(name: "marinara sauce", amount_type: unit, price: "2.50", min_amount: 1)
recipe.Product.create(name: "parseley", amount_type: unit, price: "1.00", min_amount: 1)

recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/CZLh2tI.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/avBDsUn.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/gP3nb6n.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/F6S1p.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/C45KqGY.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/6moxCeT.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/J9DLQ.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/EZh81wU.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/CeeHIIm.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/Yrp9nZu.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/5dONz.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/0YYEZqp.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/6LOAp.jpg')
recipe = Recipe.create(title: '', image_url: 'http://blog.hostthetoast.com/wp-content/uploads/2013/01/Can-Cakes-0443.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/e6I642S.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/zE0WXFG.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/ZTGqigb.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/gU2Bdn2.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/D0zIAxC.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/HNKuBK5.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/RiY8Llk.jpg')
recipe = Recipe.create(title: 'Jupitorte', image_url: 'http://bakecrumbs.files.wordpress.com/2013/07/ccjupitercake08.jpg')
recipe.Product.create(name: "flour", amount_type: unit, price: "4.50", min_amount: 1)
recipe.Product.create(name: "cocoa powder", amount_type: unit, price: "4.50", min_amount: 1)
recipe.Product.create(name: "icing", amount_type: unit, price: "2.50", min_amount: 1)
recipe.Product.create(name: "beet root powder", amount_type: unit, price: "1.00", min_amount: 1)

recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/TQ9P03b.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/aG03T.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/i3kUJ.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/fWzSE.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/p4HnQd8.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/MQWF6Re.jpg')
recipe = Recipe.create(title: '', image_url: 'http://farm8.staticflickr.com/7319/9716454028_5c1ebfc08d_k.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/RhtK0ZY.jpg')
recipe = Recipe.create(title: '', image_url: 'http://thevegetarianginger.files.wordpress.com/2013/03/dsc1251.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/AKMPeEC.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/7ekD0Kq.jpg')
recipe = Recipe.create(title: '', image_url: 'http://i.imgur.com/oPLXjDn.jpg')